name: Deploy to Coolify

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://market.a.selfhosted.hackclub.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Coolify
        uses: ./
        with:
          uuid: ${{ secrets.COOLIFY_UUID }}
          api-key: ${{ secrets.COOLIFY_API_KEY }}
          wait: 600
          tag: 'app'
